config:
  extensions:
  - $spack/var/spack/extensions/spack-linuxexternals/spack-linuxexternals
  - $spack/var/spack/extensions/spack-subspack/spack-subspack
  - $spack/var/spack/extensions/spack-mpd

